version: '3.8'
services:

  website:
    restart: always
    build: ./website
    ports:
      - "80:80"
    networks:
      - net
      
  db_server:
    restart: always
    build: ./db_server
    ports:
      - 3000:3000
    networks:
      - net
    depends_on:
      - db
  redis_server:
    restart: always
    build: ./redis_server
    ports:
      - 4000:4000
    networks:
      - net
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - net

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - net
# Names our volume

volumes:
  my-db:

networks:
  net:
