version: '3.8'
services:

  website:
    image: samurosales/noteapp_website:1.0
    restart: always
    ports:
      - "80:80"
    networks:
      - net
      
  db_server:
    restart: always
    build: ./db_server
    ports:
      - 3000:3000
    networks:
      - net
    depends_on:
      - db
  redis_server:
    restart: always
    build: ./redis_server
    ports:
      - 4000:4000
    networks:
      - net
    depends_on:
      - redis
  redis:
    restart: always
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - net

  db:
    image: mysql:5.7
    restart: always

    environment:
      MYSQL_USER: /run/secrets/db_user
      MYSQL_DATABASE: /run/secrets/db_name
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/dbr_pass
      MYSQL_PASSWORD_FILE: /run/secrets/db_pass

    # environment:
    #   MYSQL_DATABASE: 'db'
    #   # So you don't have to use root, but you can if you like
    #   MYSQL_USER: 'user'
      # You can use whatever password you like
      # MYSQL_PASSWORD: 'password'
      # # Password for root access
      # MYSQL_ROOT_PASSWORD: 'password'
    secrets:
      - db_pass
      - dbr_pass

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - net
# Names our volume

volumes:
  my-db:

networks:
  net:

secrets:
  db_pass:
    file: ./db_pass.txt
  dbr_pass:
    file: ./dbr_pass.txt

  db_name:
    file: ./db_name.txt
  db_user:
    file: ./db_user.txt
